steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=./go"]

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","hello"]
    env: ["GOPATH=./go"]

  - id: run
    name: "gcr.io/cloud-builders/go"
    args: ["build","hello"]
    env: ["GOPATH=./go"]